feat: add husky pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,14 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Define the filenames of the files to compare
+frontendSchema="packages/frontend/prisma/schema.prisma"
+backendSchema="packages/merkle_tree/prisma/schema.prisma"
+
+# check that backendSchema is strictly a subset of frontendSchema
+if ! diff --unchanged-line-format= --old-line-format='%L' "$backendSchema" "$frontendSchema" | grep -q "^"; then
+    echo "Error: $file2 is not a strict subset of $file1."
+    exit 1
+fi
+
 pnpm exec lint-staged
