Ensure prisma schema files are consistent with pre-commit hook (#37)
* feat: add husky pre-commit hook

* feat: update pre-commit hook and ensure husky runs

* chore: revert commit-msg hook

* chore: reminder about schema

---------

Co-authored-by: cha0sg0d <0xcha0sg0d@gmail.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,18 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 . "$(dirname -- "$0")/_/husky.sh"
+
+# Define the filenames of the files to compare
+frontendSchema="packages/frontend/prisma/schema.prisma"
+backendSchema="packages/merkle_tree/prisma/schema.prisma"
+
+# Read the contents of the files
+frontendContent=$(cat "$frontendSchema")
+backendContent=$(cat "$backendSchema")
+
+# Check if backendSchema is a prefix of frontendSchema
+if [[ ! "$frontendContent" =~ ^"$backendContent" ]]; then
+    echo "Error: $backendSchema is not a prefix of $frontendSchema."
+    exit 1
+fi
 
 pnpm exec lint-staged
